apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
spec:
  host: todo.apps.ocp4-mng.example.com
  path: /todo/
  port:
    targetPort: 8080
  tls:
    termination: edge
  to:
    kind: "Service"
    name: prod-frontend
